version: "3.3"
services:
### dnsmasq
  dnsmasq:
    container_name: dnsmasq
    image: nutshells/dnsmasq-fast-lookup
    #command: [ "start" ]
    ports:
      - "127.0.0.1:53:12345/udp"
    volumes:
      - type: bind
        source: <conf_dir>
        target: /usr/local/etc/dnsmasq
        read_only: true
    read_only: true
    restart: unless-stopped
