services:
  - docker

script:
  - docker-compose build

after_success:
 - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
 - docker push "${DOCKER_USERNAME}/base"
 - docker push "${DOCKER_USERNAME}/ss-obfs"
