branches:
  only:
  - master
  - travis-ci-test

git:
  depth: 1
  submodules: false

services:
  - docker

script:
  - docker-compose build --no-cache

after_success:
 - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
 - docker push "${DOCKER_USERNAME}/base"
 - docker push "${DOCKER_USERNAME}/dnscrypt-wrapper"
 - docker push "${DOCKER_USERNAME}/dnsmasq-fast-lookup"
 - docker push "${DOCKER_USERNAME}/ss-obfs"
